#  Deploy Infoledger Front to Amazon S3 and invalidate the old AWS Cloudfront distribution.

image: node:10.15.3

# Workflow Configuration

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &install-dependencies
        name: Install Dependencies
        caches:
          - node
        script:
          - npm install
    - step: &build-test-sonar
        name: Test Coverage Report
        caches:
          - node
        script:
          - npm test -- --coverage --testResultsProcessor=jest-sonar-reporter
          - pipe: sonarsource/sonarcloud-scan:1.2.1
    - step: &build-test-sonar-quality-gate
        name: Test Coverage Report & Quality Gate
        caches:
          - node
        script:
          - npm test -- --coverage --testResultsProcessor=jest-sonar-reporter
          - pipe: sonarsource/sonarcloud-scan:1.2.1
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.4
    - step: &lint
        name: Lint the node package
        script:
          - npx eslint src
        caches:
          - node
    - step: &deploy-dev
        name: Deploy to Dev
        deployment: staging
        trigger: manual
        clone:
          enabled: false
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET_STAGING
              LOCAL_PATH: 'build'
          - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID_STAGING
    - step: &deploy-prod
        name: Deploy to Prod
        deployment: production
        trigger: manual
        clone:
          enabled: false
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET_PROD
              LOCAL_PATH: 'build'
          - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID_PROD

pipelines:
  default:
    - step: *install-dependencies
    - parallel:
        - step: *build-test-sonar
        - step: *lint
  branches:
    develop:
      - step: *install-dependencies
      - parallel:
          - step: *build-test-sonar-quality-gate
          - step: *lint
      - step: *deploy-dev
  tags:
    release-*:
      - step: *install-dependencies
      - parallel:
          - step: *build-test-sonar-quality-gate
          - step: *lint
      - step: *deploy-prod
