#  Deploy Infoledger Front to Amazon S3 and invalidate the old AWS Cloudfront distribution.

image: node:10.15.3

# Workflow Configuration

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  services:
    docker:
      memory: 2048
  steps:
    - step: &install
        name: Install
        caches:
          - node
        script:
          - yarn install
    - step: &build
        name: Build
        caches:
          - node
        script:
          - yarn install
          - yarn build
        artifacts:
          - build/**
    - step: &quality-gate
        name: Quality Gate
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.4
    - step: &tests-and-sonar-cloud
        name: Tests & Sonar Cloud
        caches:
          - node
        script:
          - yarn install
          - yarn test -- --coverage --testResultsProcessor=jest-sonar-reporter
          - pipe: sonarsource/sonarcloud-scan:1.2.1
    - step: &lint
        name: Lint the code
        caches:
          - node
        script:
          - yarn install
          - npx eslint src
    - step: &deploy-dev
        name: Deploy to Dev
        deployment: staging
        trigger: manual
        clone:
          enabled: false
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET_STAGING
              LOCAL_PATH: 'build'
          - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID_STAGING
    - step: &deploy-prod
        name: Deploy to Prod
        deployment: production
        trigger: manual
        clone:
          enabled: false
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET_PROD
              LOCAL_PATH: 'build'
          - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID_PROD

pipelines:
  branches:
    develop:
      - step: *install
      - parallel:
        - step: *lint
        - step: *tests-and-sonar-cloud
      - step: *build
      - step: *deploy-dev
  tags:
    release-*:
      - step: *install
      - parallel:
          - step: *lint
          - step: *quality-gate
          - step: *tests-and-sonar-cloud
      - step: *build
      - step: *deploy-prod
