#  Deploy Infoledger Front to Amazon S3 and invalidate the old AWS Cloudfront distribution.

image: node:10.15.3

# Workflow Configuration

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm test
    - step: &sonar-cloud
        name: Sonar Cloud Scan
        script:
          - pipe: sonarsource/sonarcloud-scan:1.2.1
    - step: &lint
        name: Lint the node package
        script:
          - npm install eslint
          - npx eslint src
        caches:
          - node
    - step: &deploy-dev
        name: Deploy to Dev
        deployment: staging
        trigger: manual
        clone:
          enabled: false
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET_STAGING
              LOCAL_PATH: 'build'
          - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID_STAGING
    - step: &deploy-prod
        name: Deploy to Prod
        deployment: production
        trigger: manual
        clone:
          enabled: false
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET_PROD
              LOCAL_PATH: 'build'
          - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID_PROD

pipelines:
  default:
    - parallel:
        - step: *build-test
        - step: *sonar-cloud
        - step: *lint
  branches:
    develop:
      - parallel:
          - step: *build-test
          - step: *sonar-cloud
          - step: *lint
      - step: *deploy-dev
    master:
      - parallel:
          - step: *build-test
          - step: *sonar-cloud
          - step: *lint
      - step: *deploy-prod
