#  Deploy Infoledger Front to Amazon S3 and invalidate the old AWS Cloudfront distribution.

image: node:10.15.3

# Workflow Configuration

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  services:
    docker:
      memory: 4096
  steps:
    - step: &install-build-and-test
        name: Install & Build & Test
        script:
          - npm install
          - npm run build
          - npm test -- --coverage --testResultsProcessor=jest-sonar-reporter
          - pipe: sonarsource/sonarcloud-scan:1.2.1
        artifacts:
          - build/**
    - step: &quality-gate
        name: Quality Gate
        caches:
          - node
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.4
    - step: &lint
        name: Lint the code
        script:
          - npx eslint src
        caches:
          - node
    - step: &deploy-dev
        name: Deploy to Dev
        deployment: staging
        trigger: manual
        clone:
          enabled: false
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET_STAGING
              LOCAL_PATH: 'build'
          - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID_STAGING
    - step: &deploy-prod
        name: Deploy to Prod
        deployment: production
        trigger: manual
        clone:
          enabled: false
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET_PROD
              LOCAL_PATH: 'build'
          - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID_PROD

pipelines:
  branches:
    develop:
      - step: *install-build-and-test
      - step: *lint
      - step: *deploy-dev
  tags:
    release-*:
      - step: *install-build-and-test
      - parallel:
          - step: *quality-gate
          - step: *lint
      - step: *deploy-prod
