/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fbb1e94b-695d-402d-a2d3-3460731caba3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dnSXclPd6",
    "aws_user_pools_web_client_id": "10cr20oqg53rjv0a9g1cp1dor6",
    "oauth": {}
};


export default awsmobile;
